name: CI
on:
  push:
    branches: [ "win" ]
  pull_request:
    branches: [ "win" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup dependencies
        run: |
          cd C:\
          git clone --depth=1 --recurse-submodules https://github.com/frida/frida.git -b 16.1.11
          cd frida ; rm -r -Force ./frida-core
          git clone --depth=1 https://github.com/axojhf/frida-core.git -b SharedWin
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          cd C:\frida ; ls
          msbuild frida.sln /p:Configuration=Release /p:Platform=x64 /p:Projects="frida-core" ; ls
      - name: Package Directories
        run: |
          7z a frida-win-x64-custom.7z C:\frida\build\frida-windows\x64-Release\bin
      - name: Update modfda Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 16.1.11
          body: 'Frida 16.1.11'
          files: |
            frida-win-x64-custom.7z