name: CI
on:
  push:
    branches: [ "caddy" ]
  pull_request:
    branches: [ "caddy" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Build
        run: |
          sudo apt update && apt install -y p7zip-full
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          cd /home/runner/work/
          git clone --depth=1 --recurse-submodules https://github.com/klzgrad/forwardproxy
          cd forwardproxy
          ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=$PWD
      - name: Package Directories
        run: |
          7z a caddy.7z /home/runner/work/forwardproxy/caddy
      - uses: actions/upload-artifact@v3
        with:
          name: CaddyCustomed
          path: caddy.7z
